import {
  AlarmSmoke,
  Archive,
  Bath,
  BedDouble,
  BookOpen,
  Briefcase,
  Calendar,
  Car,
  Cctv,
  Coffee,
  CookingPot,
  Cross,
  DoorOpen,
  Droplets,
  Fan,
  Flame,
  KeyRound,
  Laptop,
  Lock,
  Microwave,
  Moon,
  PawPrint,
  Refrigerator,
  Shirt,
  Sparkles,
  Sun,
  Tv,
  UserRound,
  Utensils,
  UtensilsCrossed,
  Waves,
  Wifi,
  Wind,
  Wine,
} from 'lucide-react';

const ICONS = {
  kitchen: UtensilsCrossed,
  workspace: Laptop,
  pool: Waves,
  pets: PawPrint,
  alarm: AlarmSmoke,
  wifi: Wifi,
  parking: Car,
  hottub: Bath,
  camera: Cctv,
  smoke: AlarmSmoke,
  wind: Wind,
  fan: Fan,
  tv: Tv,
  key: KeyRound,
  lock: Lock,
  balcony: Sun,
  chair: Sun,
  fridge: Refrigerator,
  microwave: Microwave,
  stove: Flame,
  oven: CookingPot,
  coffee: Coffee,
  utensils: Utensils,
  dishes: UtensilsCrossed,
  kettle: Coffee,
  toaster: CookingPot,
  dining: Utensils,
  wine: Wine,
  bed: BedDouble,
  pillow: BedDouble,
  hanger: Shirt,
  storage: Archive,
  shades: Moon,
  iron: Shirt,
  essentials: Sparkles,
  washer: Droplets,
  dryer: Wind,
  water: Droplets,
  shampoo: Sparkles,
  soap: Droplets,
  towel: Bath,
  extinguisher: Flame,
  firstaid: Cross,
  door: DoorOpen,
  staff: UserRound,
  clean: Sparkles,
  luggage: Briefcase,
  calendar: Calendar,
  book: BookOpen,
  spark: Sparkles,
};

export function AmenityIcon({ name, size = 24 }) {
  const Icon = ICONS[name] || Sparkles;
  return <Icon size={size} strokeWidth={1.5} aria-hidden="true" />;
}
